### ISSUE TITLE
Publishing to Maven Central

### ISSUE THREAD

**Issue by ScalaWilliam** [portable-scala/sbt-platform-deps#7]
Hi @sjrd! In relation to your mention of the Scala.js SBT plug-in (https://github.com/sbt/sbt/issues/6294#issuecomment-782950628) being published on Maven Central, I tried to use it behind a firewall, and it seems this library sbt-platform-deps was not found - any chance you could publish this to Maven Central?

I believe the dependency is here in this build definition: https://github.com/scala-js/scala-js/blob/master/project/Build.scala#L1045 (did not know you could use addSbtPlugin inside settings()!)

Many thanks!

**Comment by sjrd** [comment]
I think you're conflating two issues here. The problem of publishing to Bintray is only an issue for future publications from March 1st onward. All the plugins already published are still available as is, and will be migrated as is to a different hosting before May 1st. Publishing to Maven Central will only be necessary for future versions.

If your proxy cannot resolve artifacts that are currently hosted on Bintray, you'll have to fix it on your side, because many plugins will stay where they are for a while. This plugin in particular will most likely not see another release for months or years, because it is complete. AFAICT, the first likely reason to publish a new version would be for an sbt 2.x.

**Comment by ScalaWilliam** [comment]
Thank you for getting back @sjrd, I am working with an organisation where I am trying to promote Scala, however the red tape seems to be big enough to have prevented many people from using SBT plug-ins (fortunately there are some projects which do already use Scala, but very few; many seem to have no plug-ins at all, and others may be using plugin artifacts they downloaded before the firewall was instated).

While I am working at it with a lot of effort, it appears it will be a multi-month endeavour to get SBT plugins officially included and approved the internal Artifactory (architectural/security/etc multi-level approvals). In that time, it means I can hardly promote Scala+SBT/Scala.js in its standard form because it wouldn't work for most people.

There is interest in types, the TypeScript infrastructure already works there and anybody can use it; also people do use Kotlin widely, so if Scala.js does not work in its natural form there, there is no way to promote it.

When I tried the scala-js plugin (as you mentioned it is published in Maven Central), that seems to have resolved however its dependency sbt-platform-deps would not - so hence I could not get Scala.js working. As Maven Central is approved, if this plugin were on Maven Central, it would not need any special approvals to make it work because they already have some sort of process in place.

I am of course working at the fixing the red tape, however if it 'just worked' it would make a huge difference in the timeline where I could promote more Scala. If it 'just worked' I could already be making presentations on Scala.js and a few prototypes for people to look at, however this would have to wait - and that is time in which Scala would not be gaining more hold.

Indeed this is not to do with Bintray issue, which is affecting the whole ecosystem as we have it - and is a separate although related issue.

**Comment by sjrd** [comment]
Version 1.0.1 is on its way to Maven Central.

**Comment by ScalaWilliam** [comment]
Fantastic thanks for this @sjrd !
